// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWHjWTJvgJ7X5t9wLPyOCYdkda3VyYOgI',
    appId: '1:335331728930:web:2c80b708d28dc22b62b47b',
    messagingSenderId: '335331728930',
    projectId: 'demodb-9a4ef',
    authDomain: 'demodb-9a4ef.firebaseapp.com',
    storageBucket: 'demodb-9a4ef.appspot.com',
    measurementId: 'G-PGB3E96W75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd0kb5a7U8JcA6t2EVhITLmzSg7m98xaM',
    appId: '1:335331728930:android:764df7da12f441ad62b47b',
    messagingSenderId: '335331728930',
    projectId: 'demodb-9a4ef',
    storageBucket: 'demodb-9a4ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXAxHCEDi_IUTDLtG5e5keyAio0I0fYFc',
    appId: '1:335331728930:ios:2248ac3cc2cf894262b47b',
    messagingSenderId: '335331728930',
    projectId: 'demodb-9a4ef',
    storageBucket: 'demodb-9a4ef.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXAxHCEDi_IUTDLtG5e5keyAio0I0fYFc',
    appId: '1:335331728930:ios:72329beb4b30f67f62b47b',
    messagingSenderId: '335331728930',
    projectId: 'demodb-9a4ef',
    storageBucket: 'demodb-9a4ef.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
