// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9m1gGlWNpSrm7XXfEWluH8GL771iEw9M',
    appId: '1:767476495354:web:0619f80c9e850c56102a43',
    messagingSenderId: '767476495354',
    projectId: 'practice-8fe8f',
    authDomain: 'practice-8fe8f.firebaseapp.com',
    storageBucket: 'practice-8fe8f.appspot.com',
    measurementId: 'G-EQQB5VED0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqDHpcKKWFgptodKxU1ss93nLfzzMKcZA',
    appId: '1:767476495354:android:af945cb5face8599102a43',
    messagingSenderId: '767476495354',
    projectId: 'practice-8fe8f',
    storageBucket: 'practice-8fe8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN8_rWBaSX4m8k0Bq7SnQEwpnuEj8nRww',
    appId: '1:767476495354:ios:8ebeca35006d570d102a43',
    messagingSenderId: '767476495354',
    projectId: 'practice-8fe8f',
    storageBucket: 'practice-8fe8f.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN8_rWBaSX4m8k0Bq7SnQEwpnuEj8nRww',
    appId: '1:767476495354:ios:8caa7258de5d4ac3102a43',
    messagingSenderId: '767476495354',
    projectId: 'practice-8fe8f',
    storageBucket: 'practice-8fe8f.appspot.com',
    iosBundleId: 'com.example.crud.RunnerTests',
  );
}
